job_name: "iss_now_ingestion"

extract:
  source_name: "open-notify"
  endpoint: "http://api.open-notify.org/iss-now.json"
  method: "GET"
  params: {}
  mapper: "iss_now"
  connector_type: "http_connector"

target:
  connector_type: "postgres_connector"
  execution_type: "write"
  connection: "data_warehouse"
  schema: "staging"
  table: "iss_now"
  write_mode: "append"