job_name: "iss_now_export"

extract:
  table: "iss_now"
  schema: "staging"
  connection: "data_warehouse"
  mapper: Null
  connector_type: "postgres_connector"
  execution_type: "read"

target:
  connector_type: "postgres_connector"
  execution_type: "write"
  connection: "data_warehouse"
  schema: "staging"
  table: "iss_now"
  write_mode: "append"