job_name: "iss_now_export"

extract:
  table: "iss_now"
  schema: "staging"
  connection: "data_warehouse"
  mapper: Null
  connector_type: "postgres_connector"
  execution_type: "read"

target:
  file_path: "/mnt/smb_share/alex/datastore/Exports/iss_now.json"
  file_type: "JSON"
  mapper: Null
  connector_type: "file_connector"
  execution_type: "write"
