job_name: "openweathermap_weather"

stages:
  - stage_type: "data"
    connector_type: "http_connector"
    mapper: "openweathermap_weather"
    source_name: "openweathermap"
    endpoint: "http://api.openweathermap.org/data/2.5/weather"
    method: "GET"
    params: {
      id: 2641324,
      appid: "ENVsecret"
    }
    secrets: {
      appid: "openweathermap_key"
    }

  - stage_type: "data"
    connector_type: "postgres_connector"
    execution_type: "write"
    connection: "data_warehouse"
    schema: "staging"
    table: "openweathermap_weather"
    write_mode: "append"