job_name: "metal_bands_ingestion"


stages:
  - stage_type: "data"
    connector_type: "file_connector"
    execution_type: "read"
    mapper: "metal_bands"
    source_name: "metal-bands-file"
    file_path: "/mnt/smb_share/alex/datastore/Misc/metal_bands.json"
    file_type: "JSON"
    read_type: "file"

  - stage_type: "data"
    connector_type: "postgres_connector"
    execution_type: "write"
    connection: "data_warehouse"
    schema: "staging"
    table: "metal_bands"
    write_mode: "append"